# Write your query or mutation here
query Footer {
  footer{
    content1
    Socials{
      ... on ComponentDefaultSocials{
        socials{
          link
          icon:Icon{
            name
            url
          }
        }
      }
    }
  }
}