query Post($slug: String!) {
  posts(where: {slug: $slug}) {
    id
    Title
    type
    url
    description
    Cinematographer
    productions {
      name
    }
    directors {
      Name
    }
    gallery {
      Picture {
        id
        url
      }
      id
    }
  }
}
